language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
matrix:
  include:
    - python: 2.7
      env: OLDZODB=true
    - python: 3.7
      dist: xenial
      sudo: true
install:
    - pip install -U pip setuptools
    - pip install -U zope.testrunner coverage coveralls
    - pip install -U -e .[test]
    - if [[ $OLDZODB == true ]]; then pip install 'ZODB < 5.4'; fi
script:
    - coverage run -m zope.testrunner --test-path=src
after_success:
    - coveralls
notifications:
    email: false
cache: pip
